# Generated by Django 2.2 on 2019-07-18 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wikiside',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittel', models.CharField(max_length=100)),
                ('dato_opprettet', models.DateTimeField(auto_now_add=True, verbose_name='Opprettet')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Wikisider',
            },
        ),
        migrations.CreateModel(
            name='Revisjon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('innhold', models.TextField(verbose_name='Innhold')),
                ('sist_endret', models.DateTimeField(auto_now=True, verbose_name='Sist endret')),
                ('kommentar', models.TextField(blank=True, verbose_name='Kommentar')),
                ('forfatter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('wikiside', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revisjon', to='wiki.Wikiside')),
            ],
            options={
                'verbose_name': 'Revisjon',
                'verbose_name_plural': 'Revisjoner',
                'ordering': ['-sist_endret'],
                'get_latest_by': ['sist_endret'],
            },
        ),
    ]
