# Generated by Django 2.1.7 on 2019-03-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regifant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornavn', models.CharField(max_length=100)),
                ('etternavn', models.CharField(max_length=100)),
                ('kallenavn', models.CharField(max_length=100)),
                ('foedt', models.IntegerField()),
                ('doed', models.IntegerField()),
                ('tatt_opp', models.IntegerField()),
                ('pensjonert', models.IntegerField()),
                ('mobil', models.CharField(max_length=100)),
                ('fasttelefon', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=100)),
                ('postnr', models.CharField(max_length=100)),
                ('poststed', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('hjemmeadresse', models.CharField(max_length=100)),
                ('hjemmepostnr', models.CharField(max_length=100)),
                ('hjemmepoststed', models.CharField(max_length=100)),
                ('hjemmetelefon', models.CharField(max_length=100)),
                ('jobb', models.CharField(max_length=100)),
                ('skole', models.CharField(max_length=100)),
                ('merknad', models.CharField(max_length=100)),
                ('dtp_ridder', models.IntegerField()),
                ('dtp_kommandor', models.IntegerField()),
                ('livsvarig_medlem', models.IntegerField()),
                ('mf58', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Verv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=100)),
                ('prioritet', models.IntegerField()),
                ('kort_beskrivelse', models.CharField(max_length=500)),
            ],
        ),
    ]
