# Generated by Django 2.1.7 on 2019-03-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('felixdb', '0002_auto_20190321_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regifant',
            name='dtp_kommandor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regifant',
            name='dtp_ridder',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regifant',
            name='livsvarig_medlem',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
