# Generated by Django 2.1.7 on 2019-03-21 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('felixdb', '0003_auto_20190321_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vervperiode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aar', models.IntegerField()),
                ('regifant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='felixdb.Regifant')),
                ('verv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='felixdb.Verv')),
            ],
            options={
                'verbose_name_plural': 'Vervperioder',
            },
        ),
    ]
