# Generated by Django 2.1.7 on 2019-03-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('felixdb', '0004_vervperiode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ukenavn', models.CharField(max_length=100)),
                ('aar', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Uker',
            },
        ),
    ]
