# Generated by Django 2.1.7 on 2019-03-21 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('felixdb', '0005_uke'),
    ]

    operations = [
        migrations.AddField(
            model_name='regifant',
            name='bruker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
