# Generated by Django 2.1.7 on 2019-03-21 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('felixdb', '0006_regifant_bruker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regifant',
            name='bruker',
        ),
    ]
