# Generated by Django 2.1.7 on 2019-03-25 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('felixdb', '0007_remove_regifant_bruker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ukeverv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=100)),
                ('kort_beskrivelse', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Ukeverv',
            },
        ),
        migrations.CreateModel(
            name='Ukevervperiode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regifant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='felixdb.Regifant')),
                ('uke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='felixdb.Uke')),
                ('ukeverv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='felixdb.Ukeverv')),
            ],
            options={
                'verbose_name_plural': 'Ukevervperioder',
            },
        ),
    ]
