# Generated by Django 2.1.7 on 2019-04-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('felixdb', '0008_ukeverv_ukevervperiode'),
    ]

    operations = [
        migrations.AddField(
            model_name='regifant',
            name='er_aktiv',
            field=models.BooleanField(default=True),
        ),
    ]
