# Generated by Django 2.1.7 on 2019-04-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('felixdb', '0009_regifant_er_aktiv'),
    ]

    operations = [
        migrations.AddField(
            model_name='regifant',
            name='bilde',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
