# Generated by Django 2.1.7 on 2019-04-01 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Festkassekonto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktiv', models.BooleanField(default=True, help_text='Markerer om festkassebrukeren er aktiv. Kryss av her heller enn å slette brukeren')),
                ('regiweb_bruker', models.OneToOneField(help_text='Regiweb-brukeren som denne feskassekontoen skal asossieres med', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Festkassekontoer',
            },
        ),
    ]
