# Generated by Django 2.1.7 on 2019-04-09 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gjengnavn', models.CharField(max_length=100)),
                ('barnavn', models.CharField(blank=True, max_length=100, null=True)),
                ('aktiv', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Barer',
            },
        ),
        migrations.CreateModel(
            name='BSF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beskrivelse', models.CharField(blank=True, max_length=200, null=True)),
                ('dato', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'BSFer',
            },
        ),
        migrations.CreateModel(
            name='EksternDranker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=100)),
                ('bartilhorighet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festkassen.Bar')),
            ],
            options={
                'verbose_name_plural': 'Eksterne drankere',
            },
        ),
        migrations.CreateModel(
            name='Eksternkrysseliste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dato', models.DateTimeField(default=django.utils.timezone.now)),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festkassen.Bar')),
                ('bsf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festkassen.BSF')),
                ('opprettet_av', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Eksternkrysselister',
            },
        ),
        migrations.CreateModel(
            name='EksternTransaksjon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tidsstempel', models.DateTimeField(default=django.utils.timezone.now)),
                ('antall', models.PositiveIntegerField(default=0)),
                ('stykkpris', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('eksternkrysseliste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festkassen.Eksternkrysseliste')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festkassen.EksternDranker')),
            ],
            options={
                'verbose_name_plural': 'Eksterntransaksjoner',
            },
        ),
        migrations.CreateModel(
            name='Festkassekonto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktiv', models.BooleanField(default=True, help_text='Markerer om festkassebrukeren er aktiv. Kryss av her heller enn å slette brukeren', verbose_name='Aktiv konto')),
            ],
            options={
                'verbose_name_plural': 'Festkassekontoer',
            },
        ),
        migrations.CreateModel(
            name='Festkassekontotype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=100)),
                ('svartegrense', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
            options={
                'verbose_name_plural': 'Festkassekontotyper',
            },
        ),
        migrations.CreateModel(
            name='Krysseliste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dato', models.DateTimeField(default=django.utils.timezone.now)),
                ('opprettet_av', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Krysselister',
            },
        ),
        migrations.CreateModel(
            name='Krysselistetype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=100)),
                ('beskrivelse', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Krysselistetyper',
            },
        ),
        migrations.CreateModel(
            name='Transaksjon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tidsstempel', models.DateTimeField(default=django.utils.timezone.now)),
                ('kommentar', models.CharField(blank=True, max_length=200, null=True)),
                ('festkassekonto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festkassen.Festkassekonto')),
            ],
        ),
        migrations.CreateModel(
            name='Vare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=50)),
                ('beskrivelse', models.CharField(blank=True, max_length=200, null=True)),
                ('standardpris', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('er_additiv', models.BooleanField(default=False, help_text='Hvis denne boksen er krysset av \n            vil prisen av varen LEGGES TIL festkassekontoens saldo.\n            Dersom den ikke er krysset av vil prisen TREKKES FRA\n            festkassekontoens saldo', verbose_name='Er additiv')),
            ],
            options={
                'verbose_name_plural': 'Varer',
            },
        ),
        migrations.AddField(
            model_name='krysseliste',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='festkassen.Krysselistetype'),
        ),
        migrations.AddField(
            model_name='festkassekonto',
            name='kontotype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festkassen.Festkassekontotype'),
        ),
        migrations.AddField(
            model_name='festkassekonto',
            name='regiweb_bruker',
            field=models.OneToOneField(blank=True, help_text='Regiweb-brukeren som denne feskassekontoen skal asossieres med', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eksterntransaksjon',
            name='vare',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festkassen.Vare'),
        ),
    ]
