# Generated by Django 2.1.7 on 2019-04-09 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festkassen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaksjon',
            name='festkassekonto',
        ),
        migrations.DeleteModel(
            name='Transaksjon',
        ),
    ]
