# Generated by Django 2.1.7 on 2019-04-01 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('festkassen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festkassekonto',
            name='regiweb_bruker',
            field=models.OneToOneField(blank=True, help_text='Regiweb-brukeren som denne feskassekontoen skal asossieres med', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
