# Generated by Django 2.1.7 on 2019-04-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festkassen', '0002_auto_20190401_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaksjonstype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=100)),
                ('beskrivelse', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'Transaksjonstyper',
            },
        ),
    ]
