# Generated by Django 2.1.7 on 2019-04-09 19:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('festkassen', '0002_auto_20190409_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='BSFregning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tidsstempel', models.DateTimeField(default=django.utils.timezone.now)),
                ('kommentar', models.CharField(blank=True, max_length=200, null=True)),
                ('belop', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festkassen.Bar')),
                ('bsf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festkassen.BSF')),
                ('festkassekonto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festkassen.Festkassekonto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Innskudd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tidsstempel', models.DateTimeField(default=django.utils.timezone.now)),
                ('kommentar', models.CharField(blank=True, max_length=200, null=True)),
                ('belop', models.DecimalField(decimal_places=2, max_digits=9)),
                ('godkjent', models.BooleanField(default=False)),
                ('er_utlegg', models.BooleanField(default=False)),
                ('festkassekonto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festkassen.Festkassekonto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Kryss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tidsstempel', models.DateTimeField(default=django.utils.timezone.now)),
                ('kommentar', models.CharField(blank=True, max_length=200, null=True)),
                ('antall', models.PositiveIntegerField()),
                ('stykkpris', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('festkassekonto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festkassen.Festkassekonto')),
                ('krysseliste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festkassen.Krysseliste')),
                ('vare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festkassen.Vare')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
