# Generated by Django 2.1.7 on 2019-04-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festkassen', '0003_transaksjonstype'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksjonstype',
            name='er_additiv',
            field=models.BooleanField(default=False),
        ),
    ]
