# Generated by Django 2.1.7 on 2019-04-01 12:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('festkassen', '0004_transaksjonstype_er_additiv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaksjon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tidsstempel', models.DateTimeField(default=django.utils.timezone.now)),
                ('festkassekonto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='festkassen.Festkassekonto')),
            ],
        ),
        migrations.AlterField(
            model_name='transaksjonstype',
            name='er_additiv',
            field=models.BooleanField(default=False, help_text='Dersom dette feltet er krysset av, \n                     vil transaksjoner av denne typen LEGGE TIL\n                     penger på brukerens festkassekonto. Dersom feltet\n                     IKKE er krysset vil denne typen transaksjon TREKKE FRA\n                     penger fra brukerens festkassekonto'),
        ),
        migrations.AddField(
            model_name='transaksjon',
            name='transaksjonstype',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='festkassen.Transaksjonstype'),
        ),
    ]
