# Generated by Django 2.1.7 on 2019-04-01 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('festkassen', '0005_auto_20190401_1240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaksjon',
            options={'verbose_name_plural': 'Transaksjoner'},
        ),
        migrations.AlterField(
            model_name='transaksjon',
            name='festkassekonto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festkassen.Festkassekonto'),
        ),
        migrations.AlterField(
            model_name='transaksjon',
            name='transaksjonstype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festkassen.Transaksjonstype'),
        ),
    ]
