# Generated by Django 2.1.7 on 2019-04-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festkassen', '0006_auto_20190401_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksjonstype',
            name='maa_godkjennes',
            field=models.BooleanField(default=False, help_text='\n            Kryss av dersom denne typen transaksjon må godkjennes\n            av festkasse før den skal registreres i festkassen\n            eksempelvis, så burde "innskudd" og "utlegg" godkjennes av festkasse\n        '),
        ),
        migrations.AlterField(
            model_name='transaksjonstype',
            name='er_additiv',
            field=models.BooleanField(default=False, help_text='\n            Dersom dette feltet er krysset av, \n            vil transaksjoner av denne typen LEGGE TIL\n            penger på brukerens festkassekonto. Dersom feltet\n            IKKE er krysset vil denne typen transaksjon TREKKE FRA\n            penger fra brukerens festkassekonto\n            '),
        ),
    ]
