# Generated by Django 2.1.7 on 2019-04-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festkassen', '0007_auto_20190401_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Barer',
            },
        ),
        migrations.AlterField(
            model_name='transaksjonstype',
            name='maa_godkjennes',
            field=models.BooleanField(default=False, help_text='\n            Kryss av dersom denne typen transaksjon må godkjennes\n            av festkasse før den skal registreres i festkassen.\n            eksempelvis, så burde "innskudd" og "utlegg" godkjennes av festkasse\n        ', verbose_name='Må godkjennes'),
        ),
    ]
