# Generated by Django 2.1.7 on 2019-04-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festkassen', '0008_auto_20190401_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='aktiv',
            field=models.BooleanField(default=False),
        ),
    ]
