# Generated by Django 2.1.7 on 2019-04-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festkassen', '0009_bar_aktiv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bar',
            name='navn',
        ),
        migrations.AddField(
            model_name='bar',
            name='barnavn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bar',
            name='gjengnavn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bar',
            name='aktiv',
            field=models.BooleanField(default=True),
        ),
    ]
