# Generated by Django 2.1.7 on 2019-04-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festkassen', '0010_auto_20190401_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='gjengnavn',
            field=models.CharField(default='penis', max_length=100),
            preserve_default=False,
        ),
    ]
