# Generated by Django 2.1.7 on 2019-04-01 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('festkassen', '0011_auto_20190401_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksjon',
            name='bar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='festkassen.Bar'),
        ),
    ]
