# Generated by Django 2.1.7 on 2019-04-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festkassen', '0012_transaksjon_bar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Festkassekontotype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=100)),
                ('svartegrense', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
            options={
                'verbose_name_plural': 'Festkassekontotyper',
            },
        ),
        migrations.AlterField(
            model_name='transaksjon',
            name='sum',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
