# Generated by Django 2.1.7 on 2019-04-01 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('festkassen', '0013_auto_20190401_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='festkassekonto',
            name='kontotype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='festkassen.Festkassekontotype'),
        ),
        migrations.AlterField(
            model_name='festkassekonto',
            name='aktiv',
            field=models.BooleanField(default=True, help_text='Markerer om festkassebrukeren er aktiv. Kryss av her heller enn å slette brukeren', verbose_name='Aktiv konto'),
        ),
    ]
