# Generated by Django 2.1.7 on 2019-04-01 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('festkassen', '0014_auto_20190401_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festkassekonto',
            name='kontotype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festkassen.Festkassekontotype'),
        ),
    ]
