# Generated by Django 2.1.7 on 2019-04-05 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festkassen', '0015_auto_20190401_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaksjon',
            name='bar',
        ),
        migrations.RemoveField(
            model_name='transaksjon',
            name='sum',
        ),
        migrations.RemoveField(
            model_name='transaksjon',
            name='transaksjonstype',
        ),
    ]
