# Generated by Django 2.1.7 on 2019-04-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festkassen', '0016_auto_20190405_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=50)),
                ('beskrivelse', models.CharField(blank=True, max_length=200, null=True)),
                ('pris', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
            options={
                'verbose_name_plural': 'Varer',
            },
        ),
        migrations.DeleteModel(
            name='Transaksjonstype',
        ),
    ]
