# Generated by Django 2.1.7 on 2019-04-05 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festkassen', '0017_auto_20190405_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vare',
            name='pris',
        ),
    ]
