# Generated by Django 2.1.7 on 2019-04-05 16:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('festkassen', '0018_remove_vare_pris'),
    ]

    operations = [
        migrations.CreateModel(
            name='VarePris',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pris', models.DecimalField(decimal_places=2, max_digits=7)),
                ('gyldig_fra', models.DateTimeField(default=django.utils.timezone.now)),
                ('vare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festkassen.Vare')),
            ],
            options={
                'verbose_name_plural': 'Varepriser',
            },
        ),
    ]
