# Generated by Django 2.1.7 on 2019-04-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festkassen', '0019_varepris'),
    ]

    operations = [
        migrations.AddField(
            model_name='vare',
            name='er_additiv',
            field=models.BooleanField(default=True, help_text='Hvis denne boksen er krysset av \n            vil prisen av varen LEGGES TIL festkassekontoens saldo.\n            Dersom den ikke er krysset av vil prisen trekkes fra\n            brukerens saldo', verbose_name='Er additiv'),
        ),
    ]
