# Generated by Django 2.1.7 on 2019-04-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festkassen', '0021_auto_20190406_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vare',
            name='er_additiv',
            field=models.BooleanField(default=False, help_text='Hvis denne boksen er krysset av \n            vil prisen av varen LEGGES TIL festkassekontoens saldo.\n            Dersom den ikke er krysset av vil prisen TREKKES FRA\n            festkassekontoens saldo', verbose_name='Er additiv'),
        ),
    ]
