# Generated by Django 2.1.7 on 2019-04-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festkassen', '0022_auto_20190406_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='vare',
            name='godkjent',
            field=models.BooleanField(default=False, help_text='Krysses av for å godkjenne varer, som f.eks. \n            innskudd på festkassen eller utlegg', verbose_name='Godkjent av festkasse'),
        ),
    ]
