# Generated by Django 2.1.7 on 2019-04-06 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('festkassen', '0024_auto_20190406_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksjon',
            name='antall',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaksjon',
            name='vare',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='festkassen.Vare'),
        ),
    ]
