# Generated by Django 2.1.7 on 2019-04-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festkassen', '0025_auto_20190406_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='varepris',
            name='vare',
        ),
        migrations.AddField(
            model_name='transaksjon',
            name='stykkpris',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.DeleteModel(
            name='VarePris',
        ),
    ]
