# Generated by Django 2.1.7 on 2019-04-06 14:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('festkassen', '0028_auto_20190406_1453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='krysseliste',
            options={'verbose_name_plural': 'Krysselister'},
        ),
        migrations.AlterField(
            model_name='krysseliste',
            name='dato',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
