# Generated by Django 2.1.7 on 2019-04-06 14:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('festkassen', '0029_auto_20190406_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='krysseliste',
            name='dato',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
