# Generated by Django 2.1.7 on 2019-04-06 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('festkassen', '0030_auto_20190406_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Krysselistetype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=100)),
                ('beskrivelse', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='krysseliste',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='festkassen.Krysselistetype'),
        ),
    ]
