# Generated by Django 2.1.7 on 2019-04-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festkassen', '0031_auto_20190406_1503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='krysselistetype',
            options={'verbose_name_plural': 'Krysselistetyper'},
        ),
        migrations.AlterField(
            model_name='krysselistetype',
            name='beskrivelse',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
