# Generated by Django 2.1.7 on 2019-04-07 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festkassen', '0032_auto_20190406_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='BSF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beskrivelse', models.CharField(blank=True, max_length=200, null=True)),
                ('dato', models.DateField(default=datetime.date(2019, 4, 7))),
            ],
            options={
                'verbose_name_plural': 'BSFer',
            },
        ),
    ]
