# Generated by Django 2.1.7 on 2019-04-07 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('festkassen', '0034_auto_20190407_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eksternkrysseliste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dato', models.DateTimeField(default=django.utils.timezone.now)),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festkassen.Bar')),
                ('bsf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festkassen.BSF')),
                ('opprettet_av', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Eksternkrysselister',
            },
        ),
    ]
