# Generated by Django 2.1.7 on 2019-04-07 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('festkassen', '0035_eksternkrysseliste'),
    ]

    operations = [
        migrations.CreateModel(
            name='EksterneDrankere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=100)),
                ('bartilhorighet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festkassen.Bar')),
            ],
            options={
                'verbose_name_plural': 'Eksterne drankere',
            },
        ),
    ]
