# Generated by Django 2.1.7 on 2019-04-07 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festkassen', '0036_eksternedrankere'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EksterneDrankere',
            new_name='EksternDranker',
        ),
    ]
