# Generated by Django 2.1.7 on 2019-04-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festkassen', '0037_auto_20190407_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eksterndranker',
            name='bartilhorighet',
        ),
        migrations.AddField(
            model_name='eksterndranker',
            name='bartilhorigheter',
            field=models.ManyToManyField(to='festkassen.Bar'),
        ),
    ]
