# Generated by Django 2.1.7 on 2019-04-07 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('festkassen', '0038_auto_20190407_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eksterndranker',
            name='bartilhorigheter',
        ),
        migrations.AddField(
            model_name='eksterndranker',
            name='bartilhorigheter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='festkassen.Bar'),
        ),
    ]
