# Generated by Django 2.1.7 on 2019-04-07 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festkassen', '0039_auto_20190407_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eksterndranker',
            old_name='bartilhorigheter',
            new_name='bartilhorighet',
        ),
    ]
