# Generated by Django 2.1.7 on 2019-04-07 13:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('festkassen', '0041_auto_20190407_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='EksternTransaksjon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tidsstempel', models.DateTimeField(default=django.utils.timezone.now)),
                ('antall', models.PositiveIntegerField(default=0)),
                ('stykkpris', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('eksternkrysseliste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='festkassen.Eksternkrysseliste')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='festkassen.EksternDranker')),
                ('vare', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='festkassen.Vare')),
            ],
            options={
                'verbose_name_plural': 'Eksterntransaksjoner',
            },
        ),
    ]
