# Generated by Django 2.1.7 on 2019-04-07 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('festkassen', '0043_auto_20190407_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eksterntransaksjon',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festkassen.EksternDranker'),
        ),
        migrations.AlterField(
            model_name='eksterntransaksjon',
            name='vare',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festkassen.Vare'),
        ),
    ]
