# Generated by Django 2.1.7 on 2019-04-07 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('festkassen', '0044_auto_20190407_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksjon',
            name='bar_krysset_paa',
            field=models.ForeignKey(blank=True, help_text='Bar der varen ble krysset', null=True, on_delete=django.db.models.deletion.CASCADE, to='festkassen.Bar', verbose_name='Bar'),
        ),
        migrations.AddField(
            model_name='transaksjon',
            name='ikke_krysset_paa_regi',
            field=models.BooleanField(default=False, help_text='Kryss av her hvis varen ble krysset et annet sted enn på Regi', verbose_name='Ikke krysset på Regi'),
        ),
    ]
