# Generated by Django 2.1.7 on 2019-04-07 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('festkassen', '0045_auto_20190407_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaksjon',
            name='ikke_krysset_paa_regi',
        ),
        migrations.AlterField(
            model_name='transaksjon',
            name='bar_krysset_paa',
            field=models.ForeignKey(help_text='Bar der varen ble krysset', on_delete=django.db.models.deletion.CASCADE, to='festkassen.Bar', verbose_name='Bar krysset på'),
        ),
    ]
