# Generated by Django 2.1.7 on 2019-04-07 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('festkassen', '0046_auto_20190407_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksjon',
            name='bar_krysset_paa',
            field=models.ForeignKey(blank=True, help_text='Bar der varen ble krysset', null=True, on_delete=django.db.models.deletion.CASCADE, to='festkassen.Bar', verbose_name='Bar krysset på'),
        ),
    ]
