# Generated by Django 2.1.7 on 2019-04-07 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('festkassen', '0047_auto_20190407_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaksjon',
            name='bar_krysset_paa',
        ),
        migrations.AddField(
            model_name='transaksjon',
            name='bsf_bar',
            field=models.ForeignKey(blank=True, help_text='Bar der varen ble krysset', null=True, on_delete=django.db.models.deletion.CASCADE, to='festkassen.Bar', verbose_name='BSF bar'),
        ),
    ]
