# Generated by Django 2.1.7 on 2019-04-07 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festkassen', '0048_auto_20190407_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaksjon',
            name='bsf_bar',
        ),
    ]
