# Generated by Django 2.1.7 on 2019-04-07 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('festkassen', '0049_remove_transaksjon_bsf_bar'),
    ]

    operations = [
        migrations.CreateModel(
            name='BSFRegning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festkassen.Bar')),
                ('bsf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festkassen.BSF')),
                ('festkassekonto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festkassen.Festkassekonto')),
            ],
            options={
                'verbose_name_plural': 'BSF-regninger',
            },
        ),
    ]
